name: visionmate
description: A complete AI assistant for blind users.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5
  tflite_flutter: ^0.10.1
  google_mlkit_face_detection: ^0.10.0
  flutter_tts: ^3.7.0
  speech_to_text: ^6.3.0
  permission_handler: ^10.4.3
  path_provider: ^2.0.15
  sqflite: ^2.2.8
  url_launcher: ^6.1.11
  flutter_sound: ^9.2.13
  google_maps_flutter: ^2.3.0
  geolocator: ^9.0.2
  vibration: ^1.8.3
  audioplayers: ^4.1.0
  http: ^0.13.5
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
