name: visionmate
description: A complete AI assistant for blind users.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^6.0.0
  http: ^1.3.0
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.0.0
  android_intent_plus: ^5.0.0
  wakelock_plus: ^1.2.0
  intl: ^0.19.0
  flutter_contacts: ^1.1.9
  sqflite: ^2.4.1
  path: ^1.9.0
  crypto: ^3.0.6
  battery_plus: ^6.2.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/models/
