name: visionmate
description: A complete AI assistant for blind users.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.0
  tflite_flutter: ^0.12.1
  google_mlkit_face_detection: ^0.13.2
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  url_launcher: ^6.3.1
  flutter_sound: ^9.20.5
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  vibration: ^2.0.1
  audioplayers: ^6.1.1
  http: ^1.3.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/models/
